// Code generated by github.com/whyrusleeping/cbor-gen. DO NOT EDIT.

package actor

import (
	"io"
	"math"
	"sort"

	cid "github.com/ipfs/go-cid"
	xerrors "golang.org/x/xerrors"
)

var _ = xerrors.Errorf
var _ = cid.Undef
var _ = math.E
var _ = sort.Sort

var lengthBufState = []byte{129}

func (t *State) MarshalCBOR(w io.Writer) error {
	panic("left for gen")
}

func (t *State) UnmarshalCBOR(r io.Reader) (err error) {
	panic("left for gen")
}
